version: '3'

services:
  mvccor_dbmongo:
    image: mvccordbmongo:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_mvccor_dbmongo$
    volumes:
      - D:\Project2018\MvcCor_dbMongo\MvcCor_dbMongo:/app
      - C:\Users\parinya\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_mvccor_dbmongo$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_mvccor_dbmongo$ bin/Debug/netcoreapp2.0/MvcCor_dbMongo.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
